# .streamlit/secrets.toml
# public_gsheets_url = "https://docs.google.com/spreadsheets/d/1BbRE4TU6FRoSedeZpyTpeZJE0XlgpRhvEDKESTiw4SQ/edit?usp=sharing"
# fg_analysis, 2023-04-23: https://drive.google.com/file/d/1Mf34sqSioNDsWfb4SUrA0OdPIPdP1BTE/view?usp=sharing

# protocol is:
# 1) share sheet with client_email below
# 2) make sheet public for direct reading if desired
# 3) copy sheet id into here

[data]
google_key = "1BbRE4TU6FRoSedeZpyTpeZJE0XlgpRhvEDKESTiw4SQ"
name_general = "eval_general"
name_mol     = "eval_mol"
name_details = "eval_details"
#data_rxn_key = "1QpXckkHDRW3nWUXOYmETaVCleInPx-ud"
#data_rxn_key = "1nTYrMgl3MeRIV26ztp9mVd6gVx4Y8Yss3rae4EqRgD4"      # 2023.04.21
#data_rxn_key = "1np5Jf5FgCAd1Uhna7h9v39Rx1CDDkN1-hYmmEZGF-XU"      # 2023.05.12b, fixes flips, refined ftn group definitions
#data_rxn_key = "17R0WVlzoG_TNG_KUzWO7M7EvC9w2ShP32OxOZVhuP3k"      # 2023.05.23, represent step reactions as singletons
data_rxn_key = "1eKLc5jUTv0Y7iw-WuvRlKaZXgI5v4k_F-cZs4cm9GQI"       # 2023.06.08

#fgroups_key = "1Mf34sqSioNDsWfb4SUrA0OdPIPdP1BTE"                  # 2023.04.10
#fgroups_key = "1BF9MGf3gR09j8M5xU4nHRbAuGihojzLrOHFe0aPmgHg"       # 2023.04.21
#fgroups_key = "1TI4K2vo3e0RQEbZm6I89JTguLw39BuR5XCwE-lq88_o"       # 2023.05.12b, fixes flips, refined ftn group definitions
#fgroups_key = "103eis6plakR7MrerfmkSHJ5XUsARNWQqt5nrwhqEBPQ"       # 2023.05.23, represent step reactions as singletons
fgroups_key = "1wWPBap7Y-pNilHv7WNFM_5f9hBJheEybyADmYNAC7eo"        # 2023.06.08

fgroups_sample_key = "1mRkEtxEjl8bNoJ64eAqsvaH5-To0Fz5A-vvx045iyGE"

# google cloud platform
[gcp_service_account_personal]
type = "service_account"
project_id = "maps-v0-1"
private_key_id = "51d5a7279162a31e782828bd376bb2b65a0cb871"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDI5zAq1p1cihXd\n1cxzMBidE6WIQoZy1gx1w5VW6ruXG4pdi0VSbCi3XoUKhtqO2/iC2hdb32xfJGWa\nzUrQ3CqvGRZMi8hsxQcWSHgfMGJ0VA6JQ54WpzK1Ek+FjfM5pV+G+O3ZVhXyKYyw\n7HB9nyUZ+fqxW1AdGkmU22CY1dDWAhnxs3W7ZAsisszHXef9q9JHqu7xiTEhwea3\n+nGsmG8HFh99TFSQvcJoNPMgDNBahkNsrdAjagGNA2VQhLeAIi9au8uISrj5e574\njpxG0ouWcnIDogwE912fkFauLT+kJjmSBXeecBXDAKPPuvz/YL2b3u1q3PJWOelZ\nrI+howVbAgMBAAECggEAKH8ln/T76mvxRXKz0CJJS9xqeSGDzYElKNXgdBFD+A02\nom2Q7zDbMj9MzRbq1nIz0ViZ7cyHIVSKYJ5yLtC6j+ocKxjgMUC0EYNRJ2RO7EkH\nVxb4tnNEjuhefDrlZODXdTMXasBmExbaA83dTQ034tkXdgnEh+FFJMrl2Vj8TC7r\nVQbvEavZHfHlVY4ocX/P/tIKZaDhaVZrSFrnXHUJMUa+4CczHmeNVyC4HvyVJx08\nW8lTwK3LMIwOmEt3XfXfqv/KCmWaUPhXqvr/A7sxWF1sj4Nf+mj8Lcg6nZlgp0FB\nWFfe9vPsEBtpOPaje8e6oRnJTu76p9j3l5DH95cwPQKBgQD7lIpatRPICnzAR+tn\n0kYKMdAvhZsN5CUO7r4KzSUjh8NQuytpgAL1wQZnJn9F1FAWAekGRmwgl9CGO8Cp\nPMVwAgrk1znvRP0ZURJqS/LJ+r6OYMAbvQrAFSsVNT1gVJyozLie1D1Ccb4XjaTt\nkBhigO8mVwo8fJnl29BWUoNprwKBgQDMbrtTCUew8hzZ8LINdI5mKcFqcYjxNfYg\njBBjl0RxxglygkFpJlLgmYnGqxrMVHWdEOWuzQ/Je9r1Pkr3QyKAt6906DRS8T4p\n0CrLvAaFg6iN4Lh/by0a+3iT/8rTSx7u6N/938JkFYktHK26MygaIeAy9o5SYixn\nDFVoJkLGFQKBgQDm2tViiwsN42G6Z8SCTpfqvu8UzHsN8i53V2iYLMtJoUj/CeG6\nO7d7n5aqjM75WuvqZfJYycJq3iSBKM+P/K4ILDem6kDFaP7/fj9xvyOZaDf4Gpvu\nWDhHLqWMHoClpr7ivokjZgqYsBsJLfcL79AQg9Pv0KsZ+hSWsnCo5aqlDQKBgQCO\nXFYqnv3DpPaedlUntZEsZ8t/Go0onFFHnQIUuFQ7fpM5oKd4V+3C5mjhZmoE/JPi\nys+HiNmDj7KMsdJ2mdO/GyseGE3HrKODbqk+szM/as3H70PLyln4vkHbnndZ6Kgj\n6xuAqX+vPqgGOEBquBEnEYwVMUku6ZrOL/KR0oMReQKBgBEKx8OF7ixyNO8m7u+2\n6zr5YLfEzY7ayzslWmeHh68Kr8esNolOyReIKMpmvGc13GE7mfVUESHJMSdtUCvJ\nfjexml1ESXv+RtRKfxmf14ZjqjxrOHetUoKDbstqnykBq3AFxodyjaRHcsVyWxwW\n1+Rtp85c6QdceWgCAhX6WF2q\n-----END PRIVATE KEY-----\n"
client_email = "administrator@maps-v0-1.iam.gserviceaccount.com"
client_id = "111076200048313480640"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/administrator%40maps-v0-1.iam.gserviceaccount.com"


# ucsb google cloud platform
[gcp_service_account]
type = "service_account"
project_id = "mapsv0-1"
private_key_id = "cbe9bd315b36e0d9acc312c3a075adafaf5a7576"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDKFT55uQDWGKNw\n8vqCDYeOgeuYfpapqz4TEdLDiw+4a5lKMsPcKh0azsNDstlTzYrIgTDAZhnLZloO\nQCskWFabxWDNtzjJaFCojnVOrqWLRvEN4k/57Q34DGuRIvlH55+eyKVhAXHoQaio\nOYC4i61/YVprx+mL3vuJc+zsxYjx0CQ7VJT42mqOVJ7NBeaBBYyfqYbMD3GNRMH2\nM9XuT6hrVCuk5j3IXTgf+88gmmfLBNQreNESfpHVTjESnn4Q7CppsjLb+pKaPr87\nfNqn6eetbuSeaOGHz3eavkBzJcopyZ9Z/corWBJDdl0QcPjhXpXZGWl3ZTS6UJgI\nfmySFmnJAgMBAAECggEAMr2Nz9NvjdJm63vfAZuzD0m45bPXUafhMLmXcajvnA9M\nUJCZlCTw5OPIrK1yGzQvZjPmEVExpdw/vXdIPdp+eKNhMJYSSKQMKJ6IfuakQ2nf\nKezKxwbKLJ+1vJ4K+I6EikJ4H/jUaIxf9Eln9C6CNEs2AH0UO54UC4nTkgnxXkHB\n9Wuw3rgIDbFKt+mHUkCWWcZG0ftQ1/QSUkZHQmNw9LVmlCPHNB5s+8+REsGJeaiX\nOEwCzsl2wVpHYYzkdUAe509KlWBb9fi76CfX+kuJtd4K8hKqxjitTK3VLKCQsPR1\nR8FOVwl0sro6kkcBuWV0J2BAwtAIrOKQhpaocn0QFwKBgQDzJ0em7+KdNV0x2H16\ncR8v05K7FpKndvhKa+txO+Q6caX36akm0C5QlohYaRZXuPCARdXA9gR5gg9dkmoi\nWjDznPYon1rgq96m4CR9qud/HAdAWjqmWcyXqA9iOtS6wSL+eA7kRdHN23umGAh5\nmL9nGVRTKz7I9hwtqsk2l3hhZwKBgQDUwnl3naAeN7ku2RoUZrW+s0QEzqoeJVAI\ndP/FsWPHJXXdhWPSU0icaHAk46RTGmjCDwPpfm2UI6fbOkFpGTTiQXbZ9eLzcdxr\n8maai67zyEFZyutAnmGIHWKh+cf3S4KWNQG+djVxwpPKwkapFFDn/35E3dx0ctRe\nBuF6YZztTwKBgQCIxY+IV2chBuNlJmFufjMMs/XVRt03VbRUKGBHUWkPdt3klYqQ\nSonCyunm0TXAIkcl4CJcaAYcUwxRlgodSJ5AagoMz5ZOyl5zf6EHDxsoZJuvlxFm\ngRyUMfR1TKJcakdE3EOEI8HgCZWD2ADsZP9E/vpvzeODJuyyw15rVshgAQKBgQCO\nQEDKkx89VPCBvDJNtaaKjH1L4YmogjYSkXd5jHMz8X3u0IK/W2PO/50LbRCvZ5bn\nOPbapOdLBtPyJe8Z//p11GNMs7Q8JMLFgdrMNdyRrjDTgnLsT3jScyNBPSpP07LK\nD0LNP2fYWcpK5L4tyiGWHCMmlFgTm7sV6u/SzXUIzQKBgQCmiY5t6RrcEoUMoYYD\nxoQ6doy9lpLGwNmjgZpv862UAUEH0g9gAgv5kLRS4qMdD7mvpdV2k1AWqPrcuWPU\nHGy35fasmp8sOxcYiuBfkh16Ad2Sv3+hwlx099mb63Ioys/XBmbkuLNPxrObhvJs\nL87O5XlpL4dQqeawfAh+xAVi/Q==\n-----END PRIVATE KEY-----\n"
client_email = "administrator@mapsv0-1.iam.gserviceaccount.com"
client_id = "105305843676035414898"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/administrator%40mapsv0-1.iam.gserviceaccount.com"